/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GuestService } from "../guest.service";
import { GuestCreateInput } from "./GuestCreateInput";
import { Guest } from "./Guest";
import { GuestFindManyArgs } from "./GuestFindManyArgs";
import { GuestWhereUniqueInput } from "./GuestWhereUniqueInput";
import { GuestUpdateInput } from "./GuestUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class GuestControllerBase {
  constructor(protected readonly service: GuestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Guest })
  async createGuest(@common.Body() data: GuestCreateInput): Promise<Guest> {
    return await this.service.createGuest({
      data: data,
      select: {
        contactInfo: true,
        createdAt: true,
        id: true,
        name: true,
        paymentInfo: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Guest] })
  @ApiNestedQuery(GuestFindManyArgs)
  async guests(@common.Req() request: Request): Promise<Guest[]> {
    const args = plainToClass(GuestFindManyArgs, request.query);
    return this.service.guests({
      ...args,
      select: {
        contactInfo: true,
        createdAt: true,
        id: true,
        name: true,
        paymentInfo: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Guest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async guest(
    @common.Param() params: GuestWhereUniqueInput
  ): Promise<Guest | null> {
    const result = await this.service.guest({
      where: params,
      select: {
        contactInfo: true,
        createdAt: true,
        id: true,
        name: true,
        paymentInfo: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Guest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGuest(
    @common.Param() params: GuestWhereUniqueInput,
    @common.Body() data: GuestUpdateInput
  ): Promise<Guest | null> {
    try {
      return await this.service.updateGuest({
        where: params,
        data: data,
        select: {
          contactInfo: true,
          createdAt: true,
          id: true,
          name: true,
          paymentInfo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Guest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGuest(
    @common.Param() params: GuestWhereUniqueInput
  ): Promise<Guest | null> {
    try {
      return await this.service.deleteGuest({
        where: params,
        select: {
          contactInfo: true,
          createdAt: true,
          id: true,
          name: true,
          paymentInfo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: GuestWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        checkInDate: true,
        checkOutDate: true,
        createdAt: true,

        guest: {
          select: {
            id: true,
          },
        },

        id: true,

        room: {
          select: {
            id: true,
          },
        },

        totalPrice: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: GuestWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateGuest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: GuestWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateGuest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: GuestWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateGuest({
      where: params,
      data,
      select: { id: true },
    });
  }
}
